Update tag.yml

diff --git a/.github/workflows/tag.yml b/.github/workflows/tag.yml
--- a/.github/workflows/tag.yml
+++ b/.github/workflows/tag.yml
@@ -13,30 +13,26 @@ jobs:
 
     steps:
       - name: Checkout repository
-        uses: actions/checkout@v2
+        uses: actions/checkout@v3
 
       - name: Fetch all tags and complete history
         run: |
-          git fetch --prune --unshallow --tags
-          if [ $? -ne 0 ]; then
-            echo "Failed to fetch tags and history"
-            exit 1
-          fi
+          git fetch --prune --unshallow --tags || { echo "Failed to fetch tags"; exit 1; }
 
       - name: Get the latest tag
         id: get_latest_tag
         run: |
-          latest_tag=$(git describe --tags $(git rev-list --tags --max-count=1))
-          if [ -z "$latest_tag" ]; then
-            echo "No tags found"
-            exit 1
-          fi
+          latest_tag=$(git describe --tags $(git rev-list --tags --max-count=1)) || { echo "Failed to describe tags"; exit 1; }
           echo "latest_tag=$latest_tag" >> $GITHUB_ENV
 
       - name: Determine new version
         id: new_version
         run: |
           latest_tag=${{ env.latest_tag }}
+          if [[ ! "$latest_tag" =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
+            echo "Error: Tag format is not valid. Expected format 'vX.Y.Z'."
+            exit 1
+          fi
           IFS='.' read -r major minor patch <<< "${latest_tag#v}"
           pr_title="${{ github.event.pull_request.title }}"
           case "$pr_title" in
@@ -67,11 +63,7 @@ jobs:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         run: |
           git tag -a ${{ env.new_version }} -m "Release ${{ env.new_version }}"
-          git push --tags
-          if [ $? -ne 0 ]; then
-            echo "Failed to push tag"
-            exit 1
-          fi
+          git push --tags || { echo "Failed to push tags to remote repository"; exit 1; }
 
       - name: Create GitHub Release
         uses: ncipollo/release-action@v1
